import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { spawnSync } from "node:child_process";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

// During `npm run dev`, copy artifacts to your vault on every successful
// rebuild. Skipped in production builds (use `npm run deploy` for those).
// Set NO_DEPLOY=1 in dev to opt out.
const autoDeploy = !prod && process.env.NO_DEPLOY !== "1";

const deployPlugin = {
	name: "deploy",
	setup(build) {
		build.onEnd((result) => {
			if (result.errors.length > 0) return;
			const r = spawnSync(process.execPath, ["scripts/install.mjs"], { stdio: "inherit" });
			if (r.status !== 0) {
				console.warn("(deploy step failed; build output is still in main.js)");
			}
		});
	},
};

const context = await esbuild.context({
	banner: { js: banner },
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins,
	],
	format: "cjs",
	target: "es2020",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
	plugins: autoDeploy ? [deployPlugin] : [],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
