import type { App } from "obsidian";
import { TFile } from "obsidian";
import type { PassageSegment } from "../reference/types";
import { hubFrontmatter, hubRelPath, hubTitle } from "./hub-paths";
import { lookupCrossRefs } from "../study/cross-refs-data";
import { toNumericOsisString } from "../reference/osis";
import { formatReferenceHuman, parseReference } from "../reference/parser";
import { getBookByOsis } from "../reference/books";
import { fetchBookSummary } from "../study/wikipedia";

export { hubRelPath, hubTitle } from "./hub-paths";

export type HubSeedOptions = {
	allowNetwork?: boolean;
};

async function buildBackgroundSection(seg: PassageSegment, allowNetwork: boolean): Promise<string[]> {
	if (!allowNetwork) return [];
	const summary = await fetchBookSummary(seg.bookOsis);
	if (!summary) return [];
	return [
		"## Background",
		"",
		`> ${summary.extract}`,
		"",
		`Source: [${summary.title} on Wikipedia](${summary.url}).`,
		"",
	];
}

async function buildHubBody(seg: PassageSegment, allowNetwork: boolean): Promise<string> {
	const verseKey = toNumericOsisString([seg]);
	const crossRefs = lookupCrossRefs(verseKey, 8);
	const title = hubTitle(seg.bookOsis, seg.chapter, seg.verses.start, seg.verses.end);
	const bookName = getBookByOsis(seg.bookOsis)?.name ?? seg.bookOsis;

	const sections: string[] = [];
	sections.push(`# ${title}`);
	sections.push("");
	sections.push("> [!scripture] " + formatReferenceHuman([seg]));
	sections.push("");
	sections.push("```passage");
	sections.push(formatReferenceHuman([seg]));
	sections.push("```");
	sections.push("");

	const background = await buildBackgroundSection(seg, allowNetwork);
	sections.push(...background);

	sections.push("## Cross-references");
	sections.push("");
	if (crossRefs.length === 0) {
		sections.push("_No bundled cross-refs found for this passage. Add your own here, or import a fuller dataset via Settings → Pedagogy → Cross-references extras path._");
	} else {
		for (const r of crossRefs) {
			const parsed = parseReference(r);
			const label = parsed ? formatReferenceHuman(parsed.segments) : r;
			sections.push(`- ${label}`);
		}
	}
	sections.push("");
	sections.push("## Notes");
	sections.push("");
	sections.push("");
	sections.push("## Mentioned in");
	sections.push("");
	sections.push("```dataview");
	sections.push("LIST file.link");
	sections.push(`FROM ""`);
	sections.push(
		`WHERE contains(string(passages_resolved), "${seg.bookOsis}.${seg.chapter}") OR (osis = "${seg.bookOsis}" AND chapter = ${seg.chapter})`
	);
	sections.push(`AND file.path != this.file.path`);
	sections.push("```");
	sections.push("");
	sections.push(`*Generated by Scriptorium for ${bookName} ${seg.chapter}.*`);
	sections.push("");
	return sections.join("\n");
}

export async function ensureHubNote(
	app: App,
	hubFolder: string,
	perChapter: boolean,
	seg: PassageSegment,
	options: HubSeedOptions = {}
): Promise<TFile> {
	const path = hubRelPath(hubFolder, perChapter, seg);
	const existing = app.vault.getAbstractFileByPath(path);
	if (existing instanceof TFile) return existing;
	const dir = path.split("/").slice(0, -1).join("/");
	if (dir) {
		const parts = dir.split("/").filter(Boolean);
		let acc = "";
		for (const p of parts) {
			acc = acc ? `${acc}/${p}` : p;
			if (!app.vault.getAbstractFileByPath(acc)) {
				await app.vault.createFolder(acc);
			}
		}
	}
	const allowNetwork = options.allowNetwork ?? true;
	const body = `${hubFrontmatter(seg)}\n${await buildHubBody(seg, allowNetwork)}`;
	return app.vault.create(path, body);
}
