/**
 * Bundled common-word Strong's headword data (public-domain, KJV-derived).
 *
 * Coverage: hand-curated entries for the highest-frequency words across the
 * Hebrew Bible and Greek New Testament — enough for most click/hover lookups
 * to land. Users can extend via a vault note path (see `setUserStrongs`).
 *
 * Format: number → { lemma, translit, gloss }
 */

export type StrongsEntry = {
	lemma: string;
	translit: string;
	gloss: string;
};

export const GREEK: Record<string, StrongsEntry> = {
	"1": { lemma: "Α / α", translit: "alpha", gloss: "first letter; the beginning" },
	"5": { lemma: "Ἀβραάμ", translit: "Abraam", gloss: "Abraham" },
	"11": { lemma: "ἀγαθοεργέω", translit: "agathoergeō", gloss: "to do good" },
	"18": { lemma: "ἀγαθός", translit: "agathos", gloss: "good, beneficial" },
	"19": { lemma: "ἀγαθωσύνη", translit: "agathōsunē", gloss: "goodness" },
	"25": { lemma: "ἀγαπάω", translit: "agapaō", gloss: "to love (covenant, decisive love)" },
	"26": { lemma: "ἀγάπη", translit: "agapē", gloss: "love; agape" },
	"27": { lemma: "ἀγαπητός", translit: "agapētos", gloss: "beloved" },
	"32": { lemma: "ἄγγελος", translit: "angelos", gloss: "messenger, angel" },
	"37": { lemma: "ἁγιάζω", translit: "hagiazō", gloss: "to sanctify, set apart" },
	"38": { lemma: "ἁγιασμός", translit: "hagiasmos", gloss: "sanctification, holiness" },
	"40": { lemma: "ἅγιος", translit: "hagios", gloss: "holy, set apart" },
	"42": { lemma: "ἁγιωσύνη", translit: "hagiōsunē", gloss: "holiness" },
	"71": { lemma: "ἄγω", translit: "agō", gloss: "to lead, bring" },
	"76": { lemma: "Ἀδάμ", translit: "Adam", gloss: "Adam" },
	"79": { lemma: "ἀδελφή", translit: "adelphē", gloss: "sister" },
	"80": { lemma: "ἀδελφός", translit: "adelphos", gloss: "brother, kinsman" },
	"86": { lemma: "ᾅδης", translit: "hadēs", gloss: "Hades, the realm of the dead" },
	"93": { lemma: "ἀδικία", translit: "adikia", gloss: "unrighteousness, injustice" },
	"94": { lemma: "ἄδικος", translit: "adikos", gloss: "unrighteous, unjust" },
	"129": { lemma: "αἷμα", translit: "haima", gloss: "blood" },
	"142": { lemma: "αἴρω", translit: "airō", gloss: "to take up, lift, carry away" },
	"154": { lemma: "αἰτέω", translit: "aiteō", gloss: "to ask, request" },
	"165": { lemma: "αἰών", translit: "aiōn", gloss: "age, eternity" },
	"166": { lemma: "αἰώνιος", translit: "aiōnios", gloss: "eternal, age-lasting" },
	"169": { lemma: "ἀκάθαρτος", translit: "akathartos", gloss: "unclean, impure" },
	"189": { lemma: "ἀκοή", translit: "akoē", gloss: "hearing, report" },
	"191": { lemma: "ἀκούω", translit: "akouō", gloss: "to hear, listen" },
	"225": { lemma: "ἀλήθεια", translit: "alētheia", gloss: "truth" },
	"227": { lemma: "ἀληθής", translit: "alēthēs", gloss: "true, truthful" },
	"230": { lemma: "ἀληθῶς", translit: "alēthōs", gloss: "truly, surely" },
	"235": { lemma: "ἀλλά", translit: "alla", gloss: "but, rather" },
	"240": { lemma: "ἀλλήλων", translit: "allēlōn", gloss: "one another" },
	"243": { lemma: "ἄλλος", translit: "allos", gloss: "another (of the same kind)" },
	"264": { lemma: "ἁμαρτάνω", translit: "hamartanō", gloss: "to sin, miss the mark" },
	"265": { lemma: "ἁμάρτημα", translit: "hamartēma", gloss: "sin, transgression" },
	"266": { lemma: "ἁμαρτία", translit: "hamartia", gloss: "sin" },
	"268": { lemma: "ἁμαρτωλός", translit: "hamartōlos", gloss: "sinful, sinner" },
	"281": { lemma: "ἀμήν", translit: "amēn", gloss: "truly, amen" },
	"302": { lemma: "ἄν", translit: "an", gloss: "would, might (conditional particle)" },
	"305": { lemma: "ἀναβαίνω", translit: "anabainō", gloss: "to go up, ascend" },
	"312": { lemma: "ἀναγγέλλω", translit: "anangellō", gloss: "to declare, report" },
	"314": { lemma: "ἀναγινώσκω", translit: "anaginōskō", gloss: "to read aloud" },
	"321": { lemma: "ἀνάγω", translit: "anagō", gloss: "to lead up, set sail" },
	"337": { lemma: "ἀναιρέω", translit: "anaireō", gloss: "to take up, kill" },
	"386": { lemma: "ἀνάστασις", translit: "anastasis", gloss: "resurrection, rising" },
	"435": { lemma: "ἀνήρ", translit: "anēr", gloss: "man, husband" },
	"437": { lemma: "ἀντί", translit: "anti", gloss: "against, in place of" },
	"444": { lemma: "ἄνθρωπος", translit: "anthrōpos", gloss: "human being, person" },
	"450": { lemma: "ἀνίστημι", translit: "anistēmi", gloss: "to raise up, rise" },
	"458": { lemma: "ἀνομία", translit: "anomia", gloss: "lawlessness" },
	"467": { lemma: "ἄνωθεν", translit: "anōthen", gloss: "from above, again" },
	"518": { lemma: "ἀπαγγέλλω", translit: "apangellō", gloss: "to announce, report" },
	"520": { lemma: "ἀπάγω", translit: "apagō", gloss: "to lead away" },
	"564": { lemma: "ἀπεκδέχομαι", translit: "apekdechomai", gloss: "to await eagerly" },
	"568": { lemma: "ἀπέχω", translit: "apechō", gloss: "to have in full, abstain" },
	"575": { lemma: "ἀπό", translit: "apo", gloss: "from, away from" },
	"591": { lemma: "ἀποδίδωμι", translit: "apodidōmi", gloss: "to give back, repay" },
	"599": { lemma: "ἀποθνῄσκω", translit: "apothnēskō", gloss: "to die" },
	"611": { lemma: "ἀποκρίνομαι", translit: "apokrinomai", gloss: "to answer, reply" },
	"615": { lemma: "ἀποκτείνω", translit: "apokteinō", gloss: "to kill" },
	"622": { lemma: "ἀπόλλυμι", translit: "apollumi", gloss: "to destroy, perish" },
	"630": { lemma: "ἀπολύω", translit: "apoluō", gloss: "to release, dismiss, divorce" },
	"649": { lemma: "ἀποστέλλω", translit: "apostellō", gloss: "to send forth, commission" },
	"652": { lemma: "ἀπόστολος", translit: "apostolos", gloss: "apostle, sent one" },
	"680": { lemma: "ἅπτω", translit: "haptō", gloss: "to touch, kindle" },
	"686": { lemma: "ἄρα", translit: "ara", gloss: "therefore (drawing inference)" },
	"714": { lemma: "ἀρκέω", translit: "arkeō", gloss: "to be sufficient" },
	"721": { lemma: "ἀρνίον", translit: "arnion", gloss: "lamb (esp. of Christ)" },
	"726": { lemma: "ἁρπάζω", translit: "harpazō", gloss: "to seize, snatch away" },
	"737": { lemma: "ἄρτι", translit: "arti", gloss: "now, at this moment" },
	"740": { lemma: "ἄρτος", translit: "artos", gloss: "bread, loaf" },
	"746": { lemma: "ἀρχή", translit: "archē", gloss: "beginning, ruler" },
	"749": { lemma: "ἀρχιερεύς", translit: "archiereus", gloss: "high priest" },
	"757": { lemma: "ἄρχω", translit: "archō", gloss: "to rule, begin" },
	"758": { lemma: "ἄρχων", translit: "archōn", gloss: "ruler, official" },
	"763": { lemma: "ἀσέβεια", translit: "asebeia", gloss: "ungodliness" },
	"769": { lemma: "ἀσθένεια", translit: "astheneia", gloss: "weakness, sickness" },
	"846": { lemma: "αὐτός", translit: "autos", gloss: "he, she, it; same; self" },
	"863": { lemma: "ἀφίημι", translit: "aphiēmi", gloss: "to leave, forgive, allow" },
	"906": { lemma: "βάλλω", translit: "ballō", gloss: "to throw, cast" },
	"907": { lemma: "βαπτίζω", translit: "baptizō", gloss: "to baptize, immerse" },
	"908": { lemma: "βάπτισμα", translit: "baptisma", gloss: "baptism" },
	"910": { lemma: "βαπτιστής", translit: "baptistēs", gloss: "Baptist, baptizer" },
	"932": { lemma: "βασιλεία", translit: "basileia", gloss: "kingdom, reign" },
	"935": { lemma: "βασιλεύς", translit: "basileus", gloss: "king" },
	"936": { lemma: "βασιλεύω", translit: "basileuō", gloss: "to reign" },
	"965": { lemma: "βίβλος", translit: "biblos", gloss: "book, scroll" },
	"991": { lemma: "βλέπω", translit: "blepō", gloss: "to see, look at, beware" },
	"1014": { lemma: "βούλομαι", translit: "boulomai", gloss: "to desire, intend" },
	"1064": { lemma: "γαστήρ", translit: "gastēr", gloss: "womb, belly" },
	"1067": { lemma: "γέεννα", translit: "geenna", gloss: "Gehenna, hell" },
	"1080": { lemma: "γεννάω", translit: "gennaō", gloss: "to beget, give birth, regenerate" },
	"1085": { lemma: "γένος", translit: "genos", gloss: "kind, race, family" },
	"1093": { lemma: "γῆ", translit: "gē", gloss: "earth, land" },
	"1096": { lemma: "γίνομαι", translit: "ginomai", gloss: "to become, happen, be" },
	"1097": { lemma: "γινώσκω", translit: "ginōskō", gloss: "to know, learn" },
	"1100": { lemma: "γλῶσσα", translit: "glōssa", gloss: "tongue, language" },
	"1107": { lemma: "γνωρίζω", translit: "gnōrizō", gloss: "to make known" },
	"1108": { lemma: "γνῶσις", translit: "gnōsis", gloss: "knowledge" },
	"1124": { lemma: "γραφή", translit: "graphē", gloss: "writing, scripture" },
	"1125": { lemma: "γράφω", translit: "graphō", gloss: "to write" },
	"1135": { lemma: "γυνή", translit: "gunē", gloss: "woman, wife" },
	"1138": { lemma: "Δαυίδ", translit: "Dauid", gloss: "David" },
	"1140": { lemma: "δαιμόνιον", translit: "daimonion", gloss: "demon, evil spirit" },
	"1161": { lemma: "δέ", translit: "de", gloss: "but, and (mild contrast)" },
	"1163": { lemma: "δεῖ", translit: "dei", gloss: "it is necessary, must" },
	"1188": { lemma: "δεξιός", translit: "dexios", gloss: "right (hand, side)" },
	"1208": { lemma: "δεύτερος", translit: "deuteros", gloss: "second" },
	"1209": { lemma: "δέχομαι", translit: "dechomai", gloss: "to receive, welcome" },
	"1223": { lemma: "διά", translit: "dia", gloss: "through, by means of" },
	"1228": { lemma: "διάβολος", translit: "diabolos", gloss: "devil, slanderer" },
	"1242": { lemma: "διαθήκη", translit: "diathēkē", gloss: "covenant, testament" },
	"1247": { lemma: "διακονέω", translit: "diakoneō", gloss: "to serve, minister" },
	"1248": { lemma: "διακονία", translit: "diakonia", gloss: "service, ministry" },
	"1249": { lemma: "διάκονος", translit: "diakonos", gloss: "servant, deacon" },
	"1278": { lemma: "διανοίγω", translit: "dianoigō", gloss: "to open thoroughly" },
	"1321": { lemma: "διδάσκω", translit: "didaskō", gloss: "to teach" },
	"1325": { lemma: "δίδωμι", translit: "didōmi", gloss: "to give" },
	"1342": { lemma: "δίκαιος", translit: "dikaios", gloss: "righteous, just" },
	"1343": { lemma: "δικαιοσύνη", translit: "dikaiosunē", gloss: "righteousness, justice" },
	"1344": { lemma: "δικαιόω", translit: "dikaioō", gloss: "to justify, declare righteous" },
	"1345": { lemma: "δικαίωμα", translit: "dikaiōma", gloss: "righteous decree" },
	"1377": { lemma: "διώκω", translit: "diōkō", gloss: "to pursue, persecute" },
	"1391": { lemma: "δόξα", translit: "doxa", gloss: "glory, honor" },
	"1392": { lemma: "δοξάζω", translit: "doxazō", gloss: "to glorify" },
	"1401": { lemma: "δοῦλος", translit: "doulos", gloss: "slave, servant" },
	"1410": { lemma: "δύναμαι", translit: "dunamai", gloss: "to be able, to have power" },
	"1411": { lemma: "δύναμις", translit: "dunamis", gloss: "power, miracle" },
	"1437": { lemma: "ἐάν", translit: "ean", gloss: "if (conditional)" },
	"1438": { lemma: "ἑαυτοῦ", translit: "heautou", gloss: "himself, herself, themselves" },
	"1453": { lemma: "ἐγείρω", translit: "egeirō", gloss: "to raise, awaken" },
	"1473": { lemma: "ἐγώ", translit: "egō", gloss: "I, me" },
	"1484": { lemma: "ἔθνος", translit: "ethnos", gloss: "nation, gentile" },
	"1487": { lemma: "εἰ", translit: "ei", gloss: "if" },
	"1488": { lemma: "εἶ", translit: "ei", gloss: "you are (sg. of εἰμί)" },
	"1492": { lemma: "οἶδα", translit: "oida", gloss: "to know (perfect-as-present)" },
	"1498": { lemma: "εἴη", translit: "eiē", gloss: "may be (optative)" },
	"1510": { lemma: "εἰμί", translit: "eimi", gloss: "to be" },
	"1515": { lemma: "εἰρήνη", translit: "eirēnē", gloss: "peace" },
	"1519": { lemma: "εἰς", translit: "eis", gloss: "into, toward" },
	"1520": { lemma: "εἷς", translit: "heis", gloss: "one" },
	"1525": { lemma: "εἰσέρχομαι", translit: "eiserchomai", gloss: "to go in, enter" },
	"1537": { lemma: "ἐκ", translit: "ek", gloss: "out of, from" },
	"1544": { lemma: "ἐκβάλλω", translit: "ekballō", gloss: "to cast out" },
	"1577": { lemma: "ἐκκλησία", translit: "ekklēsia", gloss: "assembly, church" },
	"1586": { lemma: "ἐκλέγομαι", translit: "eklegomai", gloss: "to choose, elect" },
	"1588": { lemma: "ἐκλεκτός", translit: "eklektos", gloss: "chosen, elect" },
	"1656": { lemma: "ἔλεος", translit: "eleos", gloss: "mercy, compassion" },
	"1680": { lemma: "ἐλπίς", translit: "elpis", gloss: "hope, expectation" },
	"1684": { lemma: "ἐμβαίνω", translit: "embainō", gloss: "to embark, step in" },
	"1715": { lemma: "ἔμπροσθεν", translit: "emprosthen", gloss: "before, in front of" },
	"1722": { lemma: "ἐν", translit: "en", gloss: "in, among" },
	"1746": { lemma: "ἐνδύω", translit: "enduō", gloss: "to clothe, put on" },
	"1781": { lemma: "ἐντέλλομαι", translit: "entellomai", gloss: "to command" },
	"1785": { lemma: "ἐντολή", translit: "entolē", gloss: "commandment" },
	"1799": { lemma: "ἐνώπιον", translit: "enōpion", gloss: "before, in the presence of" },
	"1831": { lemma: "ἐξέρχομαι", translit: "exerchomai", gloss: "to go out, depart" },
	"1849": { lemma: "ἐξουσία", translit: "exousia", gloss: "authority, right, power" },
	"1861": { lemma: "ἐπαγγέλλομαι", translit: "epangellomai", gloss: "to promise" },
	"1860": { lemma: "ἐπαγγελία", translit: "epangelia", gloss: "promise" },
	"1893": { lemma: "ἐπεί", translit: "epei", gloss: "since, because, when" },
	"1909": { lemma: "ἐπί", translit: "epi", gloss: "upon, on, at" },
	"1921": { lemma: "ἐπιγινώσκω", translit: "epiginōskō", gloss: "to recognize, fully know" },
	"1922": { lemma: "ἐπίγνωσις", translit: "epignōsis", gloss: "full knowledge" },
	"1939": { lemma: "ἐπιθυμία", translit: "epithumia", gloss: "desire, lust" },
	"1941": { lemma: "ἐπικαλέω", translit: "epikaleō", gloss: "to call upon" },
	"1979": { lemma: "ἐπίσκοπος", translit: "episkopos", gloss: "overseer, bishop" },
	"2007": { lemma: "ἐπιτίθημι", translit: "epitithēmi", gloss: "to lay upon" },
	"2036": { lemma: "εἶπον", translit: "eipon", gloss: "to say, speak (aor. of λέγω)" },
	"2046": { lemma: "ἐρέω", translit: "ereō", gloss: "to say (future of εἶπον)" },
	"2064": { lemma: "ἔρχομαι", translit: "erchomai", gloss: "to come, go" },
	"2065": { lemma: "ἐρωτάω", translit: "erōtaō", gloss: "to ask, request" },
	"2076": { lemma: "ἐστί", translit: "esti", gloss: "is (3rd sg of εἰμί)" },
	"2087": { lemma: "ἕτερος", translit: "heteros", gloss: "another (of a different kind)" },
	"2089": { lemma: "ἔτι", translit: "eti", gloss: "still, yet" },
	"2094": { lemma: "ἔτος", translit: "etos", gloss: "year" },
	"2098": { lemma: "εὐαγγέλιον", translit: "euangelion", gloss: "good news, gospel" },
	"2097": { lemma: "εὐαγγελίζω", translit: "euangelizō", gloss: "to bring good news, evangelize" },
	"2127": { lemma: "εὐλογέω", translit: "eulogeō", gloss: "to bless, speak well of" },
	"2129": { lemma: "εὐλογία", translit: "eulogia", gloss: "blessing" },
	"2147": { lemma: "εὑρίσκω", translit: "heuriskō", gloss: "to find, discover" },
	"2168": { lemma: "εὐχαριστέω", translit: "eucharisteō", gloss: "to give thanks" },
	"2192": { lemma: "ἔχω", translit: "echō", gloss: "to have, hold" },
	"2198": { lemma: "ζάω", translit: "zaō", gloss: "to live" },
	"2222": { lemma: "ζωή", translit: "zōē", gloss: "life" },
	"2228": { lemma: "ἤ", translit: "ē", gloss: "or, than" },
	"2233": { lemma: "ἡγέομαι", translit: "hēgeomai", gloss: "to lead, consider" },
	"2240": { lemma: "ἥκω", translit: "hēkō", gloss: "to have come, be present" },
	"2250": { lemma: "ἡμέρα", translit: "hēmera", gloss: "day" },
	"2316": { lemma: "θεός", translit: "theos", gloss: "God, god" },
	"2347": { lemma: "θλῖψις", translit: "thlipsis", gloss: "tribulation, affliction" },
	"2374": { lemma: "θύρα", translit: "thura", gloss: "door, gate" },
	"2378": { lemma: "θυσία", translit: "thusia", gloss: "sacrifice" },
	"2384": { lemma: "Ἰακώβ", translit: "Iakōb", gloss: "Jacob" },
	"2390": { lemma: "ἰάομαι", translit: "iaomai", gloss: "to heal" },
	"2400": { lemma: "ἰδού", translit: "idou", gloss: "behold!" },
	"2403": { lemma: "Ἰεροσόλυμα", translit: "Hierosolyma", gloss: "Jerusalem (Greek form)" },
	"2407": { lemma: "ἱερεύς", translit: "hiereus", gloss: "priest" },
	"2411": { lemma: "ἱερόν", translit: "hieron", gloss: "temple, sanctuary" },
	"2419": { lemma: "Ἰερουσαλήμ", translit: "Ierousalēm", gloss: "Jerusalem (Hebrew form)" },
	"2424": { lemma: "Ἰησοῦς", translit: "Iēsous", gloss: "Jesus, Joshua" },
	"2443": { lemma: "ἵνα", translit: "hina", gloss: "in order that, so that" },
	"2453": { lemma: "Ἰουδαῖος", translit: "Ioudaios", gloss: "Jew, Judean" },
	"2476": { lemma: "ἵστημι", translit: "histēmi", gloss: "to stand, set" },
	"2480": { lemma: "ἰσχύω", translit: "ischuō", gloss: "to be strong, prevail" },
	"2491": { lemma: "Ἰωάννης", translit: "Iōannēs", gloss: "John" },
	"2504": { lemma: "κἀγώ", translit: "kagō", gloss: "and I, even I" },
	"2509": { lemma: "καθάπερ", translit: "kathaper", gloss: "just as" },
	"2511": { lemma: "καθαρίζω", translit: "katharizō", gloss: "to cleanse" },
	"2513": { lemma: "καθαρός", translit: "katharos", gloss: "clean, pure" },
	"2521": { lemma: "κάθημαι", translit: "kathēmai", gloss: "to sit" },
	"2523": { lemma: "καθίζω", translit: "kathizō", gloss: "to seat, sit down" },
	"2532": { lemma: "καί", translit: "kai", gloss: "and, also, even" },
	"2540": { lemma: "καιρός", translit: "kairos", gloss: "appointed time, season" },
	"2548": { lemma: "κἀκεῖνος", translit: "kakeinos", gloss: "and he, that one also" },
	"2556": { lemma: "κακός", translit: "kakos", gloss: "evil, bad" },
	"2564": { lemma: "καλέω", translit: "kaleō", gloss: "to call, name" },
	"2570": { lemma: "καλός", translit: "kalos", gloss: "good, beautiful" },
	"2588": { lemma: "καρδία", translit: "kardia", gloss: "heart" },
	"2590": { lemma: "καρπός", translit: "karpos", gloss: "fruit" },
	"2596": { lemma: "κατά", translit: "kata", gloss: "down, against, according to" },
	"2597": { lemma: "καταβαίνω", translit: "katabainō", gloss: "to go down" },
	"2647": { lemma: "καταλύω", translit: "kataluō", gloss: "to destroy, lodge" },
	"2776": { lemma: "κεφαλή", translit: "kephalē", gloss: "head" },
	"2784": { lemma: "κηρύσσω", translit: "kērussō", gloss: "to proclaim, preach" },
	"2799": { lemma: "κλαίω", translit: "klaiō", gloss: "to weep" },
	"2806": { lemma: "κλάω", translit: "klaō", gloss: "to break (bread)" },
	"2813": { lemma: "κλέπτω", translit: "kleptō", gloss: "to steal" },
	"2837": { lemma: "κοιμάω", translit: "koimaō", gloss: "to sleep, fall asleep (die)" },
	"2842": { lemma: "κοινωνία", translit: "koinōnia", gloss: "fellowship, sharing" },
	"2873": { lemma: "κόπος", translit: "kopos", gloss: "labor, toil" },
	"2889": { lemma: "κόσμος", translit: "kosmos", gloss: "world, ordered system" },
	"2896": { lemma: "κράζω", translit: "krazō", gloss: "to cry out" },
	"2902": { lemma: "κρατέω", translit: "krateō", gloss: "to grasp, hold fast" },
	"2917": { lemma: "κρίμα", translit: "krima", gloss: "judgment, verdict" },
	"2919": { lemma: "κρίνω", translit: "krinō", gloss: "to judge, decide" },
	"2920": { lemma: "κρίσις", translit: "krisis", gloss: "judgment, decision" },
	"2962": { lemma: "κύριος", translit: "kurios", gloss: "Lord, master" },
	"2980": { lemma: "λαλέω", translit: "laleō", gloss: "to speak" },
	"2983": { lemma: "λαμβάνω", translit: "lambanō", gloss: "to take, receive" },
	"2992": { lemma: "λαός", translit: "laos", gloss: "people" },
	"3004": { lemma: "λέγω", translit: "legō", gloss: "to say, speak" },
	"3056": { lemma: "λόγος", translit: "logos", gloss: "word, message, reason" },
	"3107": { lemma: "μακάριος", translit: "makarios", gloss: "blessed, happy" },
	"3129": { lemma: "μανθάνω", translit: "manthanō", gloss: "to learn" },
	"3136": { lemma: "Μαρία", translit: "Maria", gloss: "Mary" },
	"3140": { lemma: "μαρτυρέω", translit: "martureō", gloss: "to bear witness, testify" },
	"3144": { lemma: "μάρτυς", translit: "martus", gloss: "witness, martyr" },
	"3173": { lemma: "μέγας", translit: "megas", gloss: "great, large" },
	"3195": { lemma: "μέλλω", translit: "mellō", gloss: "to be about to, intend" },
	"3306": { lemma: "μένω", translit: "menō", gloss: "to remain, abide" },
	"3326": { lemma: "μετά", translit: "meta", gloss: "with; after" },
	"3340": { lemma: "μετανοέω", translit: "metanoeō", gloss: "to repent, change one's mind" },
	"3341": { lemma: "μετάνοια", translit: "metanoia", gloss: "repentance" },
	"3361": { lemma: "μή", translit: "mē", gloss: "not (subjective negation)" },
	"3367": { lemma: "μηδείς", translit: "mēdeis", gloss: "no one, nothing" },
	"3384": { lemma: "μήτηρ", translit: "mētēr", gloss: "mother" },
	"3398": { lemma: "μικρός", translit: "mikros", gloss: "small, little" },
	"3403": { lemma: "μιμνῄσκομαι", translit: "mimnēskomai", gloss: "to remember" },
	"3441": { lemma: "μόνος", translit: "monos", gloss: "only, alone" },
	"3466": { lemma: "μυστήριον", translit: "mustērion", gloss: "mystery" },
	"3483": { lemma: "ναί", translit: "nai", gloss: "yes, indeed" },
	"3498": { lemma: "νεκρός", translit: "nekros", gloss: "dead" },
	"3508": { lemma: "νηστεύω", translit: "nēsteuō", gloss: "to fast" },
	"3551": { lemma: "νόμος", translit: "nomos", gloss: "law" },
	"3563": { lemma: "νοῦς", translit: "nous", gloss: "mind, understanding" },
	"3568": { lemma: "νῦν", translit: "nun", gloss: "now" },
	"3571": { lemma: "νύξ", translit: "nux", gloss: "night" },
	"3588": { lemma: "ὁ", translit: "ho", gloss: "the (definite article)" },
	"3592": { lemma: "ὅδε", translit: "hode", gloss: "this, this one" },
	"3598": { lemma: "ὁδός", translit: "hodos", gloss: "way, road, journey" },
	"3608": { lemma: "ὀθόνιον", translit: "othonion", gloss: "linen cloth" },
	"3614": { lemma: "οἰκία", translit: "oikia", gloss: "house, household" },
	"3624": { lemma: "οἶκος", translit: "oikos", gloss: "house, household" },
	"3650": { lemma: "ὅλος", translit: "holos", gloss: "whole, all" },
	"3686": { lemma: "ὄνομα", translit: "onoma", gloss: "name" },
	"3708": { lemma: "ὁράω", translit: "horaō", gloss: "to see" },
	"3716": { lemma: "ὀργή", translit: "orgē", gloss: "wrath, anger" },
	"3739": { lemma: "ὅς", translit: "hos", gloss: "who, which (relative)" },
	"3745": { lemma: "ὅσος", translit: "hosos", gloss: "as many as, as much as" },
	"3748": { lemma: "ὅστις", translit: "hostis", gloss: "whoever" },
	"3753": { lemma: "ὅτε", translit: "hote", gloss: "when" },
	"3754": { lemma: "ὅτι", translit: "hoti", gloss: "that, because" },
	"3756": { lemma: "οὐ", translit: "ou", gloss: "not (objective negation)" },
	"3762": { lemma: "οὐδείς", translit: "oudeis", gloss: "no one, nothing" },
	"3767": { lemma: "οὖν", translit: "oun", gloss: "therefore, then" },
	"3772": { lemma: "οὐρανός", translit: "ouranos", gloss: "heaven, sky" },
	"3778": { lemma: "οὗτος", translit: "houtos", gloss: "this, this one" },
	"3779": { lemma: "οὕτως", translit: "houtōs", gloss: "thus, so" },
	"3780": { lemma: "οὐχί", translit: "ouchi", gloss: "not, by no means" },
	"3784": { lemma: "ὀφείλω", translit: "opheilō", gloss: "to owe, ought" },
	"3788": { lemma: "ὀφθαλμός", translit: "ophthalmos", gloss: "eye" },
	"3793": { lemma: "ὄχλος", translit: "ochlos", gloss: "crowd, multitude" },
	"3819": { lemma: "πάλιν", translit: "palin", gloss: "again, once more" },
	"3844": { lemma: "παρά", translit: "para", gloss: "from, beside, with" },
	"3854": { lemma: "παραγίνομαι", translit: "paraginomai", gloss: "to arrive, come" },
	"3860": { lemma: "παραδίδωμι", translit: "paradidōmi", gloss: "to deliver up, betray" },
	"3870": { lemma: "παρακαλέω", translit: "parakaleō", gloss: "to comfort, exhort" },
	"3875": { lemma: "παράκλητος", translit: "paraklētos", gloss: "Paraclete, Helper" },
	"3877": { lemma: "παρακολουθέω", translit: "parakoloutheō", gloss: "to follow closely" },
	"3880": { lemma: "παραλαμβάνω", translit: "paralambanō", gloss: "to receive, take alongside" },
	"3917": { lemma: "πάρειμι", translit: "pareimi", gloss: "to be present" },
	"3918": { lemma: "παρέρχομαι", translit: "parerchomai", gloss: "to pass by, pass away" },
	"3922": { lemma: "παρθένος", translit: "parthenos", gloss: "virgin" },
	"3956": { lemma: "πᾶς", translit: "pas", gloss: "all, every" },
	"3958": { lemma: "πάσχω", translit: "paschō", gloss: "to suffer" },
	"3962": { lemma: "πατήρ", translit: "patēr", gloss: "father" },
	"3972": { lemma: "Παῦλος", translit: "Paulos", gloss: "Paul" },
	"3982": { lemma: "πείθω", translit: "peithō", gloss: "to persuade, trust" },
	"3983": { lemma: "πεινάω", translit: "peinaō", gloss: "to be hungry" },
	"3992": { lemma: "πέμπω", translit: "pempō", gloss: "to send" },
	"4012": { lemma: "περί", translit: "peri", gloss: "about, concerning" },
	"4043": { lemma: "περιπατέω", translit: "peripateō", gloss: "to walk around, conduct life" },
	"4053": { lemma: "περισσός", translit: "perissos", gloss: "abundant, exceeding" },
	"4074": { lemma: "Πέτρος", translit: "Petros", gloss: "Peter" },
	"4100": { lemma: "πιστεύω", translit: "pisteuō", gloss: "to believe, trust" },
	"4102": { lemma: "πίστις", translit: "pistis", gloss: "faith, faithfulness" },
	"4103": { lemma: "πιστός", translit: "pistos", gloss: "faithful, believing" },
	"4151": { lemma: "πνεῦμα", translit: "pneuma", gloss: "spirit, wind, breath" },
	"4160": { lemma: "ποιέω", translit: "poieō", gloss: "to do, make" },
	"4172": { lemma: "πόλις", translit: "polis", gloss: "city" },
	"4183": { lemma: "πολύς", translit: "polus", gloss: "many, much" },
	"4198": { lemma: "πορεύομαι", translit: "poreuomai", gloss: "to go, proceed" },
	"4218": { lemma: "ποτέ", translit: "pote", gloss: "once, formerly" },
	"4225": { lemma: "πού", translit: "pou", gloss: "somewhere, perhaps" },
	"4253": { lemma: "πρό", translit: "pro", gloss: "before" },
	"4267": { lemma: "προγινώσκω", translit: "proginōskō", gloss: "to foreknow" },
	"4314": { lemma: "πρός", translit: "pros", gloss: "to, toward, with" },
	"4334": { lemma: "προσέρχομαι", translit: "proserchomai", gloss: "to come to, approach" },
	"4336": { lemma: "προσεύχομαι", translit: "proseuchomai", gloss: "to pray" },
	"4352": { lemma: "προσκυνέω", translit: "proskuneō", gloss: "to worship, prostrate" },
	"4374": { lemma: "προσφέρω", translit: "prospherō", gloss: "to bring to, offer" },
	"4396": { lemma: "προφήτης", translit: "prophētēs", gloss: "prophet" },
	"4413": { lemma: "πρῶτος", translit: "prōtos", gloss: "first, foremost" },
	"4416": { lemma: "πρωτότοκος", translit: "prōtotokos", gloss: "firstborn" },
	"4441": { lemma: "πυνθάνομαι", translit: "punthanomai", gloss: "to inquire" },
	"4442": { lemma: "πῦρ", translit: "pur", gloss: "fire" },
	"4459": { lemma: "πῶς", translit: "pōs", gloss: "how?" },
	"4487": { lemma: "ῥῆμα", translit: "rhēma", gloss: "spoken word, saying" },
	"4561": { lemma: "σάρξ", translit: "sarx", gloss: "flesh" },
	"4592": { lemma: "σημεῖον", translit: "sēmeion", gloss: "sign, miracle" },
	"4612": { lemma: "Σιών", translit: "Siōn", gloss: "Zion" },
	"4716": { lemma: "σταυρός", translit: "stauros", gloss: "cross" },
	"4750": { lemma: "στόμα", translit: "stoma", gloss: "mouth" },
	"4771": { lemma: "σύ", translit: "su", gloss: "you (singular)" },
	"4772": { lemma: "συγγένεια", translit: "sungeneia", gloss: "kinship, relatives" },
	"4806": { lemma: "συζάω", translit: "suzaō", gloss: "to live together with" },
	"4862": { lemma: "σύν", translit: "sun", gloss: "with" },
	"4863": { lemma: "συνάγω", translit: "sunagō", gloss: "to gather together" },
	"4864": { lemma: "συναγωγή", translit: "sunagōgē", gloss: "synagogue, assembly" },
	"4920": { lemma: "συνίημι", translit: "suniēmi", gloss: "to understand" },
	"4982": { lemma: "σῴζω", translit: "sōzō", gloss: "to save, deliver" },
	"4990": { lemma: "σωτήρ", translit: "sōtēr", gloss: "savior" },
	"4991": { lemma: "σωτηρία", translit: "sōtēria", gloss: "salvation" },
	"5021": { lemma: "τάσσω", translit: "tassō", gloss: "to appoint, ordain" },
	"5034": { lemma: "ταχύ", translit: "tachu", gloss: "quickly, soon" },
	"5043": { lemma: "τέκνον", translit: "teknon", gloss: "child" },
	"5046": { lemma: "τέλειος", translit: "teleios", gloss: "complete, perfect" },
	"5048": { lemma: "τελειόω", translit: "teleioō", gloss: "to make perfect, complete" },
	"5055": { lemma: "τελέω", translit: "teleō", gloss: "to complete, finish" },
	"5056": { lemma: "τέλος", translit: "telos", gloss: "end, goal" },
	"5087": { lemma: "τίθημι", translit: "tithēmi", gloss: "to put, place" },
	"5088": { lemma: "τίκτω", translit: "tiktō", gloss: "to bear, give birth" },
	"5091": { lemma: "τιμάω", translit: "timaō", gloss: "to honor" },
	"5092": { lemma: "τιμή", translit: "timē", gloss: "honor, value" },
	"5100": { lemma: "τις", translit: "tis", gloss: "someone, anyone" },
	"5101": { lemma: "τίς", translit: "tis", gloss: "who? what? which?" },
	"5117": { lemma: "τόπος", translit: "topos", gloss: "place, location" },
	"5119": { lemma: "τότε", translit: "tote", gloss: "then" },
	"5140": { lemma: "τρεῖς", translit: "treis", gloss: "three" },
	"5207": { lemma: "υἱός", translit: "huios", gloss: "son" },
	"5210": { lemma: "ὑμεῖς", translit: "humeis", gloss: "you (plural)" },
	"5217": { lemma: "ὑπάγω", translit: "hupagō", gloss: "to go away, depart" },
	"5219": { lemma: "ὑπακούω", translit: "hupakouō", gloss: "to obey" },
	"5228": { lemma: "ὑπέρ", translit: "huper", gloss: "for, on behalf of" },
	"5259": { lemma: "ὑπό", translit: "hupo", gloss: "by, under" },
	"5278": { lemma: "ὑπομένω", translit: "hupomenō", gloss: "to endure, persevere" },
	"5281": { lemma: "ὑπομονή", translit: "hupomonē", gloss: "endurance, perseverance" },
	"5290": { lemma: "ὑποστρέφω", translit: "hupostrephō", gloss: "to return" },
	"5316": { lemma: "φαίνω", translit: "phainō", gloss: "to shine, appear" },
	"5319": { lemma: "φανερόω", translit: "phaneroō", gloss: "to manifest, reveal" },
	"5346": { lemma: "φημί", translit: "phēmi", gloss: "to say, affirm" },
	"5368": { lemma: "φιλέω", translit: "phileō", gloss: "to love, have affection" },
	"5384": { lemma: "φίλος", translit: "philos", gloss: "friend" },
	"5399": { lemma: "φοβέομαι", translit: "phobeomai", gloss: "to fear, reverence" },
	"5408": { lemma: "φόβος", translit: "phobos", gloss: "fear" },
	"5417": { lemma: "φρονέω", translit: "phroneō", gloss: "to think, set the mind on" },
	"5442": { lemma: "φυλάσσω", translit: "phulassō", gloss: "to guard, keep" },
	"5457": { lemma: "φῶς", translit: "phōs", gloss: "light" },
	"5463": { lemma: "χαίρω", translit: "chairō", gloss: "to rejoice" },
	"5479": { lemma: "χαρά", translit: "chara", gloss: "joy" },
	"5485": { lemma: "χάρις", translit: "charis", gloss: "grace, favor" },
	"5495": { lemma: "χείρ", translit: "cheir", gloss: "hand" },
	"5547": { lemma: "Χριστός", translit: "Christos", gloss: "Christ, Anointed" },
	"5550": { lemma: "χρόνος", translit: "chronos", gloss: "time, period" },
	"5590": { lemma: "ψυχή", translit: "psuchē", gloss: "soul, life" },
	"5613": { lemma: "ὡς", translit: "hōs", gloss: "as, like, when" },
	"5618": { lemma: "ὥσπερ", translit: "hōsper", gloss: "just as" },
	"5619": { lemma: "ὡσαύτως", translit: "hōsautōs", gloss: "in the same way, likewise" },
	"5625": { lemma: "ἤτοι", translit: "ētoi", gloss: "either, or" },
};

export const HEBREW: Record<string, StrongsEntry> = {
	"1": { lemma: "אָב", translit: "ʾab", gloss: "father" },
	"3": { lemma: "אָבַד", translit: "ʾabad", gloss: "to perish, be destroyed" },
	"5": { lemma: "אֲבַדּוֹן", translit: "ʾabaddon", gloss: "destruction, Abaddon" },
	"6": { lemma: "אָבַד", translit: "ʾabad", gloss: "to wander, perish" },
	"19": { lemma: "אָבִיב", translit: "ʾabib", gloss: "fresh ear of grain; Abib (month)" },
	"50": { lemma: "אֵבֶל", translit: "ʾebel", gloss: "mourning" },
	"68": { lemma: "אֶבֶן", translit: "ʾeben", gloss: "stone" },
	"85": { lemma: "אַבְרָהָם", translit: "ʾAbraham", gloss: "Abraham" },
	"113": { lemma: "אָדוֹן", translit: "ʾadon", gloss: "lord, master" },
	"120": { lemma: "אָדָם", translit: "ʾadam", gloss: "man, mankind, Adam" },
	"127": { lemma: "אֲדָמָה", translit: "ʾadamah", gloss: "ground, earth" },
	"136": { lemma: "אֲדֹנָי", translit: "ʾadonay", gloss: "Lord, my Lord" },
	"157": { lemma: "אָהַב", translit: "ʾahab", gloss: "to love" },
	"160": { lemma: "אַהֲבָה", translit: "ʾahabah", gloss: "love" },
	"168": { lemma: "אֹהֶל", translit: "ʾohel", gloss: "tent" },
	"175": { lemma: "אַהֲרֹן", translit: "ʾAharon", gloss: "Aaron" },
	"183": { lemma: "אָוָה", translit: "ʾavah", gloss: "to desire, long for" },
	"205": { lemma: "אָוֶן", translit: "ʾaven", gloss: "wickedness, trouble" },
	"216": { lemma: "אוֹר", translit: "ʾor", gloss: "light" },
	"226": { lemma: "אוֹת", translit: "ʾot", gloss: "sign, mark" },
	"227": { lemma: "אָז", translit: "ʾaz", gloss: "then, at that time" },
	"241": { lemma: "אֹזֶן", translit: "ʾozen", gloss: "ear" },
	"251": { lemma: "אָח", translit: "ʾach", gloss: "brother" },
	"259": { lemma: "אֶחָד", translit: "ʾechad", gloss: "one, unique" },
	"269": { lemma: "אָחוֹת", translit: "ʾachot", gloss: "sister" },
	"270": { lemma: "אָחַז", translit: "ʾachaz", gloss: "to grasp, seize" },
	"310": { lemma: "אַחַר", translit: "ʾachar", gloss: "after, behind" },
	"312": { lemma: "אַחֵר", translit: "ʾacher", gloss: "another, other" },
	"347": { lemma: "אִיּוֹב", translit: "ʾIyyov", gloss: "Job" },
	"376": { lemma: "אִישׁ", translit: "ʾish", gloss: "man, husband" },
	"398": { lemma: "אָכַל", translit: "ʾakal", gloss: "to eat" },
	"408": { lemma: "אַל", translit: "ʾal", gloss: "do not (with jussive)" },
	"410": { lemma: "אֵל", translit: "ʾel", gloss: "God, mighty" },
	"413": { lemma: "אֶל", translit: "ʾel", gloss: "to, toward" },
	"430": { lemma: "אֱלֹהִים", translit: "ʾelohim", gloss: "God, gods" },
	"433": { lemma: "אֱלוֹהַּ", translit: "ʾeloah", gloss: "God (singular)" },
	"452": { lemma: "אֵלִיָּהוּ", translit: "ʾEliyyahu", gloss: "Elijah" },
	"518": { lemma: "אִם", translit: "ʾim", gloss: "if, whether" },
	"539": { lemma: "אָמַן", translit: "ʾaman", gloss: "to be firm, believe" },
	"543": { lemma: "אָמֵן", translit: "ʾamen", gloss: "amen, truly" },
	"559": { lemma: "אָמַר", translit: "ʾamar", gloss: "to say, speak" },
	"571": { lemma: "אֱמֶת", translit: "ʾemet", gloss: "truth, faithfulness" },
	"582": { lemma: "אֱנוֹשׁ", translit: "ʾenosh", gloss: "man, humanity (mortal)" },
	"587": { lemma: "אֲנַחְנוּ", translit: "ʾanachnu", gloss: "we" },
	"589": { lemma: "אֲנִי", translit: "ʾani", gloss: "I" },
	"595": { lemma: "אָנֹכִי", translit: "ʾanoki", gloss: "I (emphatic)" },
	"622": { lemma: "אָסַף", translit: "ʾasap", gloss: "to gather" },
	"631": { lemma: "אָסַר", translit: "ʾasar", gloss: "to bind" },
	"637": { lemma: "אַף", translit: "ʾap", gloss: "anger, nostril; also" },
	"639": { lemma: "אַף", translit: "ʾap", gloss: "nose, anger" },
	"657": { lemma: "אֶפֶס", translit: "ʾepes", gloss: "end, ceasing" },
	"669": { lemma: "אֶפְרַיִם", translit: "ʾEphraim", gloss: "Ephraim" },
	"685": { lemma: "אֲרוֹן", translit: "ʾaron", gloss: "ark, chest" },
	"727": { lemma: "אֲרוֹן", translit: "ʾaron", gloss: "ark of the covenant" },
	"749": { lemma: "אֲרַם", translit: "ʾAram", gloss: "Aram, Syria" },
	"776": { lemma: "אֶרֶץ", translit: "ʾerets", gloss: "land, earth" },
	"784": { lemma: "אֵשׁ", translit: "ʾesh", gloss: "fire" },
	"802": { lemma: "אִשָּׁה", translit: "ʾishah", gloss: "woman, wife" },
	"803": { lemma: "אֲשֻׁרָה", translit: "ʾashurah", gloss: "step, going" },
	"834": { lemma: "אֲשֶׁר", translit: "ʾasher", gloss: "who, which, that" },
	"853": { lemma: "אֵת", translit: "ʾet", gloss: "(direct object marker)" },
	"854": { lemma: "אֵת", translit: "ʾet", gloss: "with" },
	"905": { lemma: "בַּד", translit: "bad", gloss: "alone, separation" },
	"926": { lemma: "בָּהַל", translit: "bahal", gloss: "to be terrified" },
	"929": { lemma: "בְּהֵמָה", translit: "behemah", gloss: "beast, cattle" },
	"935": { lemma: "בּוֹא", translit: "boʾ", gloss: "to come, go in" },
	"956": { lemma: "בּוּז", translit: "buz", gloss: "to despise" },
	"977": { lemma: "בָּחַר", translit: "bachar", gloss: "to choose" },
	"982": { lemma: "בָּטַח", translit: "batach", gloss: "to trust" },
	"995": { lemma: "בִּין", translit: "bin", gloss: "to discern, understand" },
	"998": { lemma: "בִּינָה", translit: "binah", gloss: "understanding" },
	"1004": { lemma: "בַּיִת", translit: "bayit", gloss: "house" },
	"1058": { lemma: "בָּכָה", translit: "bakah", gloss: "to weep" },
	"1077": { lemma: "בַּל", translit: "bal", gloss: "not" },
	"1086": { lemma: "בָּלָה", translit: "balah", gloss: "to wear out" },
	"1115": { lemma: "בִּלְתִּי", translit: "bilti", gloss: "not, except" },
	"1121": { lemma: "בֵּן", translit: "ben", gloss: "son" },
	"1129": { lemma: "בָּנָה", translit: "banah", gloss: "to build" },
	"1145": { lemma: "בֶּן־יְמִינִי", translit: "Ben-Yemini", gloss: "Benjamite" },
	"1162": { lemma: "בֹּעַז", translit: "Boʿaz", gloss: "Boaz" },
	"1167": { lemma: "בַּעַל", translit: "baʿal", gloss: "owner, master, husband; Baal" },
	"1242": { lemma: "בֹּקֶר", translit: "boqer", gloss: "morning" },
	"1245": { lemma: "בָּקַשׁ", translit: "baqash", gloss: "to seek" },
	"1254": { lemma: "בָּרָא", translit: "baraʾ", gloss: "to create" },
	"1285": { lemma: "בְּרִית", translit: "berit", gloss: "covenant" },
	"1288": { lemma: "בָּרַךְ", translit: "barak", gloss: "to bless, kneel" },
	"1293": { lemma: "בְּרָכָה", translit: "berakah", gloss: "blessing" },
	"1320": { lemma: "בָּשָׂר", translit: "basar", gloss: "flesh" },
	"1323": { lemma: "בַּת", translit: "bat", gloss: "daughter" },
	"1349": { lemma: "גָּאוֹן", translit: "gaʾon", gloss: "majesty, pride" },
	"1350": { lemma: "גָּאַל", translit: "gaʾal", gloss: "to redeem" },
	"1366": { lemma: "גְּבוּל", translit: "gebul", gloss: "border, territory" },
	"1368": { lemma: "גִּבּוֹר", translit: "gibbor", gloss: "mighty, hero" },
	"1377": { lemma: "גְּבִירָה", translit: "gebirah", gloss: "queen, mistress" },
	"1419": { lemma: "גָּדוֹל", translit: "gadol", gloss: "great" },
	"1431": { lemma: "גָּדַל", translit: "gadal", gloss: "to grow, magnify" },
	"1471": { lemma: "גּוֹי", translit: "goy", gloss: "nation, gentile" },
	"1481": { lemma: "גּוּר", translit: "gur", gloss: "to sojourn, dwell as alien" },
	"1494": { lemma: "גָּזַז", translit: "gazaz", gloss: "to shear" },
	"1540": { lemma: "גָּלָה", translit: "galah", gloss: "to uncover, reveal, exile" },
	"1546": { lemma: "גָּלוּת", translit: "galut", gloss: "exile" },
	"1571": { lemma: "גַּם", translit: "gam", gloss: "also, even" },
	"1612": { lemma: "גֶּפֶן", translit: "gepen", gloss: "vine" },
	"1697": { lemma: "דָּבָר", translit: "dabar", gloss: "word, thing, matter" },
	"1696": { lemma: "דָּבַר", translit: "dabar", gloss: "to speak" },
	"1732": { lemma: "דָּוִד", translit: "Dawid", gloss: "David" },
	"1875": { lemma: "דָּרַשׁ", translit: "darash", gloss: "to seek, inquire" },
	"1870": { lemma: "דֶּרֶךְ", translit: "derek", gloss: "way, road" },
	"1933": { lemma: "הָוָה", translit: "havah", gloss: "to be, become" },
	"1961": { lemma: "הָיָה", translit: "hayah", gloss: "to be, happen" },
	"1980": { lemma: "הָלַךְ", translit: "halak", gloss: "to walk, go" },
	"1984": { lemma: "הָלַל", translit: "halal", gloss: "to praise; also boast" },
	"2009": { lemma: "הִנֵּה", translit: "hinneh", gloss: "behold!" },
	"2022": { lemma: "הַר", translit: "har", gloss: "mountain, hill" },
	"2088": { lemma: "זֶה", translit: "zeh", gloss: "this" },
	"2142": { lemma: "זָכַר", translit: "zakar", gloss: "to remember" },
	"2145": { lemma: "זָכָר", translit: "zakar", gloss: "male" },
	"2233": { lemma: "זֶרַע", translit: "zeraʿ", gloss: "seed, offspring" },
	"2308": { lemma: "חָדַל", translit: "chadal", gloss: "to cease, leave off" },
	"2398": { lemma: "חָטָא", translit: "chataʾ", gloss: "to sin, miss" },
	"2403": { lemma: "חַטָּאת", translit: "chaṭṭaʾt", gloss: "sin, sin offering" },
	"2416": { lemma: "חַי", translit: "chai", gloss: "living, alive" },
	"2421": { lemma: "חָיָה", translit: "chayah", gloss: "to live" },
	"2425": { lemma: "חָיַי", translit: "chayay", gloss: "to live, revive" },
	"2428": { lemma: "חַיִל", translit: "chayil", gloss: "strength, army, valor" },
	"2451": { lemma: "חָכְמָה", translit: "chokmah", gloss: "wisdom" },
	"2455": { lemma: "חָכָם", translit: "chakam", gloss: "wise" },
	"2470": { lemma: "חָלָה", translit: "chalah", gloss: "to be sick, weak" },
	"2486": { lemma: "חָלִילָה", translit: "chalilah", gloss: "far be it!" },
	"2530": { lemma: "חָמַד", translit: "chamad", gloss: "to desire, covet" },
	"2603": { lemma: "חָנַן", translit: "chanan", gloss: "to be gracious" },
	"2580": { lemma: "חֵן", translit: "chen", gloss: "favor, grace" },
	"2617": { lemma: "חֶסֶד", translit: "chesed", gloss: "lovingkindness, covenant loyalty" },
	"2620": { lemma: "חָסָה", translit: "chasah", gloss: "to take refuge" },
	"2654": { lemma: "חָפֵץ", translit: "chapets", gloss: "to delight in" },
	"2790": { lemma: "חָרַשׁ", translit: "charash", gloss: "to be silent; engrave" },
	"2820": { lemma: "חָשַׂךְ", translit: "chasak", gloss: "to withhold, restrain" },
	"2822": { lemma: "חֹשֶׁךְ", translit: "choshek", gloss: "darkness" },
	"2896": { lemma: "טוֹב", translit: "tov", gloss: "good" },
	"2945": { lemma: "טַף", translit: "tap", gloss: "little ones, family" },
	"3027": { lemma: "יָד", translit: "yad", gloss: "hand" },
	"3045": { lemma: "יָדַע", translit: "yadaʿ", gloss: "to know" },
	"3050": { lemma: "יָהּ", translit: "Yah", gloss: "Yah (short for YHWH)" },
	"3068": { lemma: "יְהֹוָה", translit: "YHWH", gloss: "Yahweh, the LORD" },
	"3069": { lemma: "יְהֹוִה", translit: "YHWH (Adonai vowels)", gloss: "the LORD (with Adonai vowels)" },
	"3091": { lemma: "יְהוֹשֻׁעַ", translit: "Yehoshua", gloss: "Joshua, Yeshua" },
	"3092": { lemma: "יְהוֹשָׁפָט", translit: "Yehoshaphat", gloss: "Jehoshaphat" },
	"3117": { lemma: "יוֹם", translit: "yom", gloss: "day" },
	"3119": { lemma: "יוֹמָם", translit: "yomam", gloss: "by day, daily" },
	"3162": { lemma: "יַחַד", translit: "yachad", gloss: "together, in unity" },
	"3190": { lemma: "יָטַב", translit: "yatab", gloss: "to be good, do well" },
	"3220": { lemma: "יָם", translit: "yam", gloss: "sea, west" },
	"3225": { lemma: "יָמִין", translit: "yamin", gloss: "right hand, south" },
	"3254": { lemma: "יָסַף", translit: "yasap", gloss: "to add, increase" },
	"3290": { lemma: "יַעֲקֹב", translit: "Yaʿaqov", gloss: "Jacob" },
	"3318": { lemma: "יָצָא", translit: "yatsaʾ", gloss: "to go out" },
	"3320": { lemma: "יָצַב", translit: "yatsav", gloss: "to take a stand" },
	"3331": { lemma: "יָצַע", translit: "yatsaʿ", gloss: "to spread out" },
	"3372": { lemma: "יָרֵא", translit: "yareʾ", gloss: "to fear, reverence" },
	"3373": { lemma: "יָרֵא", translit: "yareʾ", gloss: "fearing, reverent" },
	"3374": { lemma: "יִרְאָה", translit: "yirʾah", gloss: "fear, reverence" },
	"3381": { lemma: "יָרַד", translit: "yarad", gloss: "to go down" },
	"3389": { lemma: "יְרוּשָׁלִַם", translit: "Yerushalayim", gloss: "Jerusalem" },
	"3423": { lemma: "יָרַשׁ", translit: "yarash", gloss: "to inherit, possess" },
	"3427": { lemma: "יָשַׁב", translit: "yashav", gloss: "to sit, dwell" },
	"3444": { lemma: "יְשׁוּעָה", translit: "yeshuʿah", gloss: "salvation, deliverance" },
	"3467": { lemma: "יָשַׁע", translit: "yashaʿ", gloss: "to save, deliver" },
	"3474": { lemma: "יָשָׁר", translit: "yashar", gloss: "upright, just" },
	"3478": { lemma: "יִשְׂרָאֵל", translit: "Yisraʾel", gloss: "Israel" },
	"3499": { lemma: "יֶתֶר", translit: "yeter", gloss: "remainder, excess" },
	"3548": { lemma: "כֹּהֵן", translit: "kohen", gloss: "priest" },
	"3559": { lemma: "כּוּן", translit: "kun", gloss: "to establish, prepare" },
	"3588": { lemma: "כִּי", translit: "ki", gloss: "for, because, when" },
	"3605": { lemma: "כֹּל", translit: "kol", gloss: "all, every" },
	"3615": { lemma: "כָּלָה", translit: "kalah", gloss: "to be complete, finish" },
	"3627": { lemma: "כְּלִי", translit: "keli", gloss: "vessel, implement" },
	"3651": { lemma: "כֵּן", translit: "ken", gloss: "thus, so" },
	"3680": { lemma: "כָּסָה", translit: "kasah", gloss: "to cover" },
	"3701": { lemma: "כֶּסֶף", translit: "keseph", gloss: "silver, money" },
	"3722": { lemma: "כָּפַר", translit: "kaphar", gloss: "to atone, cover" },
	"3724": { lemma: "כֹּפֶר", translit: "kopher", gloss: "ransom, price of life" },
	"3725": { lemma: "כִּפֻּר", translit: "kippur", gloss: "atonement" },
	"3742": { lemma: "כְּרוּב", translit: "kerub", gloss: "cherub" },
	"3772": { lemma: "כָּרַת", translit: "karat", gloss: "to cut, cut off; cut a covenant" },
	"3789": { lemma: "כָּתַב", translit: "katab", gloss: "to write" },
	"3808": { lemma: "לֹא", translit: "loʾ", gloss: "no, not" },
	"3820": { lemma: "לֵב", translit: "lev", gloss: "heart, mind" },
	"3824": { lemma: "לֵבָב", translit: "levav", gloss: "heart, inner self" },
	"3947": { lemma: "לָקַח", translit: "laqach", gloss: "to take, receive" },
	"3956": { lemma: "לָשׁוֹן", translit: "lashon", gloss: "tongue" },
	"3966": { lemma: "מְאֹד", translit: "meʾod", gloss: "very, exceedingly" },
	"3967": { lemma: "מֵאָה", translit: "meʾah", gloss: "hundred" },
	"4057": { lemma: "מִדְבָּר", translit: "midbar", gloss: "wilderness, desert" },
	"4191": { lemma: "מוּת", translit: "mut", gloss: "to die" },
	"4194": { lemma: "מָוֶת", translit: "mavet", gloss: "death" },
	"4150": { lemma: "מוֹעֵד", translit: "moʿed", gloss: "appointed time, festival" },
	"4196": { lemma: "מִזְבֵּחַ", translit: "mizbeach", gloss: "altar" },
	"4310": { lemma: "מִי", translit: "mi", gloss: "who?" },
	"4325": { lemma: "מַיִם", translit: "mayim", gloss: "water" },
	"4399": { lemma: "מְלָאכָה", translit: "melaʾkah", gloss: "work, occupation" },
	"4397": { lemma: "מַלְאָךְ", translit: "malʾak", gloss: "messenger, angel" },
	"4421": { lemma: "מִלְחָמָה", translit: "milchamah", gloss: "war, battle" },
	"4427": { lemma: "מָלַךְ", translit: "malak", gloss: "to reign, be king" },
	"4428": { lemma: "מֶלֶךְ", translit: "melek", gloss: "king" },
	"4467": { lemma: "מַמְלָכָה", translit: "mamlakah", gloss: "kingdom" },
	"4480": { lemma: "מִן", translit: "min", gloss: "from" },
	"4492": { lemma: "מָסַךְ", translit: "masak", gloss: "to cover, screen" },
	"4525": { lemma: "מַסֵּכָה", translit: "massekah", gloss: "molten image" },
	"4549": { lemma: "מָסַס", translit: "masas", gloss: "to melt, dissolve" },
	"4639": { lemma: "מַעֲשֶׂה", translit: "maʿaseh", gloss: "deed, work" },
	"4687": { lemma: "מִצְוָה", translit: "mitsvah", gloss: "commandment" },
	"4714": { lemma: "מִצְרַיִם", translit: "Mitsrayim", gloss: "Egypt" },
	"4720": { lemma: "מִקְדָּשׁ", translit: "miqdash", gloss: "sanctuary" },
	"4872": { lemma: "מֹשֶׁה", translit: "Mosheh", gloss: "Moses" },
	"4912": { lemma: "מָשַׁל", translit: "mashal", gloss: "to rule" },
	"4941": { lemma: "מִשְׁפָּט", translit: "mishpat", gloss: "judgment, justice" },
	"4994": { lemma: "נָא", translit: "naʾ", gloss: "please, now (particle)" },
	"5002": { lemma: "נְאֻם", translit: "neʾum", gloss: "utterance, oracle" },
	"5030": { lemma: "נָבִיא", translit: "naviʾ", gloss: "prophet" },
	"5046": { lemma: "נָגַד", translit: "nagad", gloss: "to declare, tell" },
	"5066": { lemma: "נָגַשׁ", translit: "nagash", gloss: "to draw near" },
	"5117": { lemma: "נוּחַ", translit: "nuach", gloss: "to rest" },
	"5158": { lemma: "נַחַל", translit: "nachal", gloss: "stream, valley" },
	"5162": { lemma: "נָחַם", translit: "nacham", gloss: "to be sorry, comfort" },
	"5186": { lemma: "נָטָה", translit: "natah", gloss: "to stretch out, incline" },
	"5234": { lemma: "נָכַר", translit: "nakar", gloss: "to recognize, regard" },
	"5252": { lemma: "נָסַב", translit: "nasav", gloss: "to surround, turn" },
	"5265": { lemma: "נָסַע", translit: "nasaʿ", gloss: "to set out, journey" },
	"5307": { lemma: "נָפַל", translit: "nafal", gloss: "to fall" },
	"5315": { lemma: "נֶפֶשׁ", translit: "nephesh", gloss: "soul, life, person" },
	"5337": { lemma: "נָצַל", translit: "natsal", gloss: "to deliver, snatch away" },
	"5375": { lemma: "נָשָׂא", translit: "nasaʾ", gloss: "to lift, carry, bear" },
	"5414": { lemma: "נָתַן", translit: "natan", gloss: "to give, set, place" },
	"5439": { lemma: "סָבִיב", translit: "saviv", gloss: "around, surrounding" },
	"5493": { lemma: "סוּר", translit: "sur", gloss: "to turn aside" },
	"5650": { lemma: "עֶבֶד", translit: "ʿeved", gloss: "servant, slave" },
	"5674": { lemma: "עָבַר", translit: "ʿavar", gloss: "to pass over" },
	"5712": { lemma: "עֵדָה", translit: "ʿedah", gloss: "congregation" },
	"5704": { lemma: "עַד", translit: "ʿad", gloss: "until, as far as" },
	"5749": { lemma: "עוּד", translit: "ʿud", gloss: "to bear witness" },
	"5769": { lemma: "עוֹלָם", translit: "ʿolam", gloss: "forever, eternity, age" },
	"5775": { lemma: "עוֹף", translit: "ʿop", gloss: "bird, fowl" },
	"5800": { lemma: "עָזַב", translit: "ʿazav", gloss: "to forsake, leave" },
	"5826": { lemma: "עָזַר", translit: "ʿazar", gloss: "to help" },
	"5828": { lemma: "עֵזֶר", translit: "ʿezer", gloss: "help, helper" },
	"5869": { lemma: "עַיִן", translit: "ʿayin", gloss: "eye, fountain" },
	"5892": { lemma: "עִיר", translit: "ʿir", gloss: "city" },
	"5921": { lemma: "עַל", translit: "ʿal", gloss: "upon, above, against" },
	"5927": { lemma: "עָלָה", translit: "ʿalah", gloss: "to go up, ascend" },
	"5930": { lemma: "עוֹלָה", translit: "ʿolah", gloss: "burnt offering" },
	"5971": { lemma: "עַם", translit: "ʿam", gloss: "people, nation" },
	"5973": { lemma: "עִם", translit: "ʿim", gloss: "with" },
	"5975": { lemma: "עָמַד", translit: "ʿamad", gloss: "to stand" },
	"6030": { lemma: "עָנָה", translit: "ʿanah", gloss: "to answer, respond; afflict" },
	"6031": { lemma: "עָנָה", translit: "ʿanah", gloss: "to be afflicted" },
	"6213": { lemma: "עָשָׂה", translit: "ʿasah", gloss: "to do, make" },
	"6235": { lemma: "עֶשֶׂר", translit: "ʿeser", gloss: "ten" },
	"6256": { lemma: "עֵת", translit: "ʿet", gloss: "time, season" },
	"6258": { lemma: "עַתָּה", translit: "ʿattah", gloss: "now" },
	"6299": { lemma: "פָּדָה", translit: "padah", gloss: "to redeem, ransom" },
	"6310": { lemma: "פֶּה", translit: "peh", gloss: "mouth" },
	"6440": { lemma: "פָּנִים", translit: "panim", gloss: "face, presence" },
	"6485": { lemma: "פָּקַד", translit: "paqad", gloss: "to visit, attend to" },
	"6680": { lemma: "צָוָה", translit: "tsavah", gloss: "to command, charge" },
	"6743": { lemma: "צָלַח", translit: "tsalach", gloss: "to prosper, succeed" },
	"6663": { lemma: "צָדַק", translit: "tsadaq", gloss: "to be righteous" },
	"6664": { lemma: "צֶדֶק", translit: "tsedeq", gloss: "righteousness" },
	"6666": { lemma: "צְדָקָה", translit: "tsedaqah", gloss: "righteousness, justice" },
	"6726": { lemma: "צִיּוֹן", translit: "Tsiyyon", gloss: "Zion" },
	"6817": { lemma: "צָעַק", translit: "tsaʿaq", gloss: "to cry out" },
	"6908": { lemma: "קָבַץ", translit: "qavats", gloss: "to gather" },
	"6912": { lemma: "קָבַר", translit: "qavar", gloss: "to bury" },
	"6918": { lemma: "קָדוֹשׁ", translit: "qadosh", gloss: "holy" },
	"6942": { lemma: "קָדַשׁ", translit: "qadash", gloss: "to be holy, set apart" },
	"6944": { lemma: "קֹדֶשׁ", translit: "qodesh", gloss: "holiness, holy thing" },
	"6963": { lemma: "קוֹל", translit: "qol", gloss: "voice, sound" },
	"6965": { lemma: "קוּם", translit: "qum", gloss: "to arise, stand" },
	"6973": { lemma: "קוּץ", translit: "quts", gloss: "to loathe" },
	"7121": { lemma: "קָרָא", translit: "qaraʾ", gloss: "to call, proclaim, read" },
	"7126": { lemma: "קָרַב", translit: "qarav", gloss: "to draw near" },
	"7130": { lemma: "קֶרֶב", translit: "qerev", gloss: "midst, inward part" },
	"7138": { lemma: "קָרוֹב", translit: "qarov", gloss: "near" },
	"7200": { lemma: "רָאָה", translit: "raʾah", gloss: "to see" },
	"7218": { lemma: "רֹאשׁ", translit: "roʾsh", gloss: "head" },
	"7225": { lemma: "רֵאשִׁית", translit: "reʾshit", gloss: "beginning, first" },
	"7227": { lemma: "רַב", translit: "rav", gloss: "great, many, abundant" },
	"7235": { lemma: "רָבָה", translit: "ravah", gloss: "to be many, multiply" },
	"7307": { lemma: "רוּחַ", translit: "ruach", gloss: "spirit, wind, breath" },
	"7311": { lemma: "רוּם", translit: "rum", gloss: "to be high, exalt" },
	"7355": { lemma: "רָחַם", translit: "racham", gloss: "to have compassion" },
	"7356": { lemma: "רַחֲמִים", translit: "rachamim", gloss: "compassion, mercies" },
	"7363": { lemma: "רָחַף", translit: "rachap", gloss: "to hover" },
	"7368": { lemma: "רָחַק", translit: "rachaq", gloss: "to be far" },
	"7392": { lemma: "רָכַב", translit: "rakav", gloss: "to ride" },
	"7451": { lemma: "רָע", translit: "raʿ", gloss: "evil, bad" },
	"7455": { lemma: "רֹעַ", translit: "roaʿ", gloss: "evil, badness" },
	"7462": { lemma: "רָעָה", translit: "raʿah", gloss: "to feed, shepherd" },
	"7563": { lemma: "רָשָׁע", translit: "rasha'", gloss: "wicked, guilty" },
	"7665": { lemma: "שָׁבַר", translit: "shavar", gloss: "to break" },
	"7686": { lemma: "שָׁגָה", translit: "shagah", gloss: "to go astray" },
	"7725": { lemma: "שׁוּב", translit: "shuv", gloss: "to return, repent" },
	"7760": { lemma: "שׂוּם", translit: "sum", gloss: "to put, place" },
	"7812": { lemma: "שָׁחָה", translit: "shachah", gloss: "to bow down, worship" },
	"7843": { lemma: "שָׁחַת", translit: "shachat", gloss: "to corrupt, destroy" },
	"7846": { lemma: "שֵׂט", translit: "set", gloss: "rebellion" },
	"7892": { lemma: "שִׁיר", translit: "shir", gloss: "song" },
	"7919": { lemma: "שָׂכַל", translit: "sakal", gloss: "to be prudent, understand" },
	"7965": { lemma: "שָׁלוֹם", translit: "shalom", gloss: "peace, wholeness" },
	"7971": { lemma: "שָׁלַח", translit: "shalach", gloss: "to send" },
	"8010": { lemma: "שְׁלֹמֹה", translit: "Shelomoh", gloss: "Solomon" },
	"8064": { lemma: "שָׁמַיִם", translit: "shamayim", gloss: "heavens, sky" },
	"8074": { lemma: "שָׁמֵם", translit: "shamem", gloss: "to be desolate" },
	"8085": { lemma: "שָׁמַע", translit: "shamaʿ", gloss: "to hear, obey" },
	"8104": { lemma: "שָׁמַר", translit: "shamar", gloss: "to keep, guard" },
	"8136": { lemma: "שִׁמָּשׁ", translit: "shimmash", gloss: "to serve" },
	"8141": { lemma: "שָׁנָה", translit: "shanah", gloss: "year" },
	"8147": { lemma: "שְׁנַיִם", translit: "shenayim", gloss: "two" },
	"8197": { lemma: "שֶׁפֶט", translit: "shephet", gloss: "judgment" },
	"8199": { lemma: "שָׁפַט", translit: "shaphat", gloss: "to judge" },
	"8210": { lemma: "שָׁפַךְ", translit: "shaphak", gloss: "to pour out" },
	"8267": { lemma: "שֶׁקֶר", translit: "sheqer", gloss: "lie, falsehood" },
	"8269": { lemma: "שַׂר", translit: "sar", gloss: "prince, ruler" },
	"8451": { lemma: "תּוֹרָה", translit: "torah", gloss: "instruction, law, Torah" },
	"8615": { lemma: "תִּקְוָה", translit: "tiqvah", gloss: "hope, expectation" },
	"8669": { lemma: "תְּשׁוּקָה", translit: "teshuqah", gloss: "longing, desire" },
};

const userExtraGreek: Record<string, StrongsEntry> = {};
const userExtraHebrew: Record<string, StrongsEntry> = {};
let downloadedGreek: Record<string, StrongsEntry> | null = null;
let downloadedHebrew: Record<string, StrongsEntry> | null = null;

export function setUserStrongs(map: { greek?: Record<string, StrongsEntry>; hebrew?: Record<string, StrongsEntry> }): void {
	for (const k of Object.keys(userExtraGreek)) delete userExtraGreek[k];
	for (const k of Object.keys(userExtraHebrew)) delete userExtraHebrew[k];
	if (map.greek) Object.assign(userExtraGreek, map.greek);
	if (map.hebrew) Object.assign(userExtraHebrew, map.hebrew);
}

export function setDownloadedStrongs(map: {
	greek?: Record<string, StrongsEntry>;
	hebrew?: Record<string, StrongsEntry>;
}): void {
	downloadedGreek = map.greek ?? null;
	downloadedHebrew = map.hebrew ?? null;
}

export function downloadedStrongsCount(): { greek: number; hebrew: number } {
	return {
		greek: downloadedGreek ? Object.keys(downloadedGreek).length : 0,
		hebrew: downloadedHebrew ? Object.keys(downloadedHebrew).length : 0,
	};
}

/**
 * Look up a Strong's entry. Resolution order:
 *   1. User-supplied vault-note extras (highest precedence)
 *   2. Bundled common-words starter set
 *   3. Downloaded full lexicon (when present)
 */
export function lookupStrongs(kind: "G" | "H", num: string): StrongsEntry | null {
	const n = num.replace(/^0+/, "") || num;
	if (kind === "G") return userExtraGreek[n] ?? GREEK[n] ?? downloadedGreek?.[n] ?? null;
	return userExtraHebrew[n] ?? HEBREW[n] ?? downloadedHebrew?.[n] ?? null;
}
